apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos-web
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: videos-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: videos-web
    spec:
      containers:
      - name: videos-web-container
        image: oumaymacharrad/videos-webapp:1.0.6@sha256:bedb8d61cb60768e41b5f403c0b56dc83585c73903dc4bdb741b2beaf4b9b824 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /index.php
            port: 80
        envFrom:
            - configMapRef:
                name: frontend-env
        securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            seccompProfile:
              type: RuntimeDefault


